# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104edb41ab1cbf7a7d37abef0c647f0b7652a107e2f49a645e62d87684f2377c96b2444a2e424c4edd05062f7bce4c83e2d485f61cae4507c5db10843a4c41cd

test:
  secret_key_base: 5547b4243dda81d81221f4f77e3fef792e9ec61be3cf6d8814435cd1af0fd7cc7461c0e0cd4c020ffdc7918991d056a76f280c9ade044225a80761aa6d882d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
